### ISSUE TITLE
Possible to transpile ts

### ISSUE THREAD

**Issue by wenerme** [esbuild-kit/tsx#106]
### Feature request

e.g.

```ts
import {a} from 'dep'
```

```json
{
  "name":"dep",
  "exports": {".":{
    "typescript":"./src/index.ts",
    "import":"./lib/esm/index.js",
    "require":"./lib/cjs/index.js"
  }}
}
```

When using tsx, I want to pickup `typescript` instead of `import` or `require`

### Why?

- When dev, I may just link or deps on a git repo without prebuild, there is no ./lib/esm/index.js
- When dev, import from ts is faster to try and fail without another build or watch

### Additional context

Using tsx with ava by `--loader=tsx`, want to iterate faster.

**Comment by privatenumber** [comment]
You can do this in Node.js using the [`conditions` flag](https://nodejs.org/api/cli.html#-ccondition---conditionscondition).

I do something similar with import maps:
https://twitter.com/privatenumbr/status/1541677849412882434

With tsx, flags are passed down to Node.js so you can do:
```
tsx --conditions=typescript ./file.ts
```

**Comment by wenerme** [comment]
@privatenumber how can I pass this when using `--loader` ?

**Comment by privatenumber** [comment]
It's a Node CLI so you can pass it in the same way you would any other CLI flag:
```
node --loader tsx --conditions=typescript ./file.ts
```

**Comment by fox1t** [comment]
@privatenumber, what about adding this to the docs? This is very important for the DX in monorepos. I came up with this same idea too much time. Having it written in the docs would make life easier. Let me know if you want me to open the PR

**Comment by privatenumber** [comment]
The reason it's not documented is that it's neither a tsx feature nor relevant to the enhancements tsx adds to Node.js.

In other words, tsx doesn't include any code to support `--conditions` and it has no consideration for it. We just got it for free when Node.js added it, and it doesn't make sense to document something that Node.js inherently provides. While documenting frequently used scenarios could be valuable, there's too many Node.js features and use-cases that are considered common (especially before `--conditions`).

The current documentation does indicate that flags are propagated to Node.js:
https://github.com/esbuild-kit/tsx#:~:text=All%20command%2Dline%20arguments%20(with%20the%20exception%20of%20a%20few)%20are%20propagated%20to%20Node.js.

Could improving the docs to better guide users toward consulting the Node.js documentation be a beneficial step?

**Comment by fox1t** [comment]
I 100% agree with you. That's why we should find the correct wording to add it (if we want to add it at all).
This specific configuration is essential for monorepo environments and, finally, allowed us to properly have the dev server, run by tsx, to restarts automatically on `packages/*` save. This enables a zero-config, blazingly fast DX in TS monorepo, thanks to tsx.
We might add a "Monorepo" section to the doc and say that everything works out of the box thanks to the interop with Node.js. Personally, I am a massive fan of the "cheat sheet" sections, and it might be worth considering adding an easy-to-copy-paste code. For example, this cheat sheet is fantastic that adds valuable content to the above documentation: https://vitest.dev/guide/mocking.html#cheat-sheet
