### ISSUE TITLE
feat: Is it compatible with __dirname or import.meta.url

### ISSUE THREAD

**Issue by rxliuli** [esbuild-kit/tsx#120]
### Feature request

Currently, the error occurs when using `__dirname` in esm or `import.meta.env` in cjs, but I actually want to be able to run since they are convertible to each other.

tsup provides a `--shims` option for compatibility(https://tsup.egoist.dev/#inject-cjs-and-esm-shims), vitest Also compatible, I hope tsx can be compatible with this situation by default

example

```ts
console.log(__dirname)

export {}
```

### Why?

```sh
ReferenceError: __dirname is not defined in ES module scope
```

**Comment by privatenumber** [comment]
You can run your Node.js project in CJS mode to use `__dirname` in ESM code.

When tsx detects a ESM file, it runs it directly with Node.js without interfering with it so it doesn't have an opportunity to inject it (it's also not apart of ESM spec so it will not be supported). However, it will be available in ESM code running in a CJS context because it gets provided by Node.js. Perhaps this is why it works in some environments.

Also, tsx adds `import.meta.url` to JS files in a CJS context. Using `import` indicates that it's ESM code that needs to be transformed to CJS.
