### ISSUE TITLE
Support API JavaScript

### ISSUE THREAD

**Issue by tachibana-shin** [esbuild-kit/tsx#13]
Hi,

I think it would be great to have a JavaScript API for other compilers to use like `tsup`

Like it:
```ts
import { build } from "tsx"

build({
  entry: "src/main.ts",
  watch: true
})
```

**Comment by tachibana-shin** [comment]
I am creating a framework and it needs a command to run typescript in development mode. I am intending to use `tsx` to run the compiled typescript script

**Comment by privatenumber** [comment]
You mean the _uncompiled_ TypeScript code.

In your code, you can currently:
- spawn a tsx process
- use the new loader we just deployed: https://github.com/esbuild-kit/tsx/pull/9

I'll considering exporting a method that spawns tsx given a file path. But the JS API will e limited to a spawn because it needs to be read by the [Loader API](https://nodejs.org/api/esm.html#loaders).

Would love to hear more about your use-case when you have more details.

**Comment by privatenumber** [comment]
I believe the output stream needs to be TTY for colors to be outputted.

You can inherit the stdout to display colors: https://github.com/esbuild-kit/tsx/blob/a271f4d1773bfb0ffdd072aa36e996c6e8602b32/src/run.ts#L21-L25

**Comment by tachibana-shin** [comment]
![image](https://user-images.githubusercontent.com/45375496/169425501-29633591-b4bd-44f8-ba04-b5c665e6b8fb.png)
I found out when there is a syntax error on the files it seems that `tsx` itself doesn't have the error color

**Comment by tachibana-shin** [comment]
by the way can you review this pull request https://github.com/esbuild-kit/esm-loader/pull/11

**Comment by privatenumber** [comment]
Back to the original request.

You can now spawn a tsx process without losing color in stderr.

Is this request closable?

**Comment by tachibana-shin** [comment]
Closed
