### ISSUE TITLE
Support named imports for JSON

### ISSUE THREAD

**Issue by antfu** [esbuild-kit/tsx#2]
https://stackblitz.com/edit/node-ewwreq

**Comment by privatenumber** [comment]
This problem is happening because Node.js is unable to detect whether a `.ts` file is `commonjs`/`module`.

I worked on a fix in https://github.com/esbuild-kit/esm-loader/pull/2, which detects the package type (by detecting nearest `package.json`), and skips it if it's `commonjs`, so that it can be handled by `cjs-loader`.

When the fix is merged, named imports on JSON will work for CommonJS contexts.

However, it still won't work in Module contexts because [native JSON modules don't support named imports by spec](https://github.com/tc39/proposal-json-modules#:~:text=the%20resulting%20json%20object%20is%20the%20default%20export%20of%20the%20module%20(which%20has%20no%20named%20exports).). We can technically override this behavior to support it but I'm not sure if we should because we don't back-port things like `__filename`/`__dirname`.

What do you think?

**Comment by antfu** [comment]
I think using named import json is quite a common convention supported by most of the bundlers. Importing a single field of a json would also enable tree-shaking for a smaller footprint. I would expect this as I might run the .ts file with the runtime in development and use bundler for production. Without this, it would be quite a hassle to deal with. I am not sure if sacrificing this to match the spec is worth it here.

**Comment by privatenumber** [comment]
Fair point. I actually encountered that exact problem when importing `version` from `package.json`, which works in Rollup/Vite.

I'm OK with overriding JSON modules to add support in esm-loader as well.

For reference on bundlers:
- Rollup's JSON plugin has [named exports enabled](https://github.com/rollup/plugins/tree/master/packages/json#namedexports) by default. Seems this is what [Vite uses too](https://github.com/vitejs/vite/blob/274c10eb9e9451620981da808e143bc50b8c2a38/packages/vite/rollup.config.js#L7).

- Webpack 5 started to [disallow named imports](https://webpack.js.org/blog/2020-10-10-webpack-5-release/#:~:text=json%20modules%20now%20align%20with%20the%20proposal%20and%20emit%20a%20warning%20when%20a%20non-default%20export%20is%20used.%20json%20modules%20no%20longer%20have%20named%20exports%20when%20importing%20from%20a%20strict%20ecmascript%20module.) on JSON modules. Webpack 5 has really good [CommonJS tree-shaking](https://webpack.js.org/blog/2020-10-10-webpack-5-release/#commonjs-tree-shaking) so they don't often incur extra costs. However, I don't think Webpack is a common bundler for Node.js targets.
