### ISSUE TITLE
Add `clearScreen` in watch mode

### ISSUE THREAD

**Issue by patheticGeek** [esbuild-kit/tsx#25]
I have a monorepo setup, and I am using a command to parallelly run my server and client.
Server uses `tsx watch` to run and when they both run, tsx clears the console, so client's output is also being cleared, which is not the desired behavior.

**Comment by patheticGeek** [comment]
@privatenumber Can you take a look at this please?

**Comment by privatenumber** [comment]
Based on what you provided, Im not convinced this is a real problem or that this is the best solution.

On Mac at least, it doesn't completely clear the terminal. You can still scroll up to see the output.

And clearing the terminal is a pretty common behavior in watch mode. If this is a common problem, how do other popular programs handle this?

Feel free to elaborate and provide more research, use-cases, and justification by editing the post.

**Comment by patheticGeek** [comment]
> Based on what you provided, Im not convinced this is a real problem or that this is the best solution.
> 
> On Mac at least, it doesn't completely clear the terminal. You can still scroll up to see the output.

For me on linux, it does clear the terminal and even if it just moved the output above, it is still not ideal to have that behavior.

> And clearing the terminal is a pretty common behavior in watch mode. If this is a common problem, how do other popular programs handle this?

What I use currently is nodemon, and it has the following behavior, by default it doesn't clear the terminal.
![image](https://user-images.githubusercontent.com/11344611/171064321-d98df664-932a-4c26-b07c-13955936f7f0.png)

> Feel free to elaborate and provide more research, use-cases, and justification by editing the post.

tsx clearing the console isn't a problem when you are only using tsx, but when you wanna run two commands parallel, you don't expect one to clear or move the console on restart (at least this is what I think personally.
We can discuss a better solution, as this was something I did quickly for my use case.

**Comment by knpwrs** [comment]
I am in a similar situation except I am running multiple services through `docker-compose`. Printing the screen clear escape code clears the output from all of my other docker services. Merging #23 would be a great solution for me.

> You can still scroll up to see the output.

This assumes a standalone terminal not running in any sort of multiplexer such as `screen` or `tmux`. Running in `tmux` I would have to enter scroll mode just to see output from services unrelated to what I'm using `tsx` for. This is cumbersome in many situations including startup where a service might fail to start but I don't see why it's failing.

It seems odd to me for `tsx` to want to clear the screen. It makes sense in tools like `jest` because their watch mode is interactive. I would expect `tsx` to act more like `ts-node-dev`.
