### ISSUE TITLE
Make tsx work with Jest

### ISSUE THREAD

**Issue by lcswillems** [esbuild-kit/tsx#258]
### Feature request

tsx doesn't seem to work with Jest, and it would be great if it was the case.

### Why?

No need anymore to install these additional packages:

```
"@swc/core": "^1.3.46",
"@swc/jest": "^0.2.24",
```

**Comment by privatenumber** [comment]
Jest runs on Node.js, so in that sense, it can be run using tsx. But if you mean loading TypeScript files within Jest, then I think it's out of scope since Jest has its own module resolver.

I don't use Jest and I'm not familiar enough with it's API but if it can be supported in a trivial way (e.g. Node.js loaders), I'd be open to considering it. Closing but happy to re-open given research that demonstrates the effort.
