### ISSUE TITLE
importing and exporting an interface fails for type module in package.json and ESXXXX module in tsconfig.json

### ISSUE THREAD

**Issue by stefanrusu-loctax** [esbuild-kit/tsx#272]
### Bug description

I tried tsx against a codebase where an interface is imported by a module, then re-exported. Basically it fails with:

```
npm start

> start
> npx tsx index.ts

~/source/tsx-repro/index.ts:1
import { Interf } from './interf.js';
         ^

SyntaxError: The requested module './interf.js' does not provide an export named 'Interf'
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:124:21)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ModuleJob.run (node:internal/modules/esm/module_job:190:5)
```

See linked gist with the minimal context to reproduce this issue.

This doesn't happen with `ts-node` in ESM mode nor with `esbuild`. Basically, I piped the `esbuild`'s STDOUT to `node`'s STDIN and the whole codebase runs as expected. So, this behaviour is particular to `tsx`.

Basically, anything from ES2015 to ESNext compilerOptions module in tsconfig.json and package.json `"type": "module"` triggers this failure when importing and exporting an interface. It does not happen if it imports and exports a function for example.

### Reproduction

https://gist.github.com/stefanrusu-loctax/8e02e07bc18d00a29c33b045d93a15a9

### Environment

```shell
System:
    OS: macOS 12.6.7
    CPU: (8) arm64 Apple M1 Pro
    Memory: 91.78 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.16.0 - ~/.nodenv/versions/18.16.0/bin/node
    npm: 9.5.1 - ~/.nodenv/versions/18.16.0/bin/npm
    pnpm: 7.32.2 - ~/.nodenv/versions/18.16.0/bin/pnpm
  npmPackages:
    tsx: ^3.12.7 => 3.12.7
```

### Can you work on a fix?

- [ ] I’m interested in opening a pull request to address this issue.

**Comment by privatenumber** [comment]
This is expected behavior and is consistent with TypeScript:

- `interf.ts` exports a type (an interface), which doesn't have a runtime value so it's stripped by the TypeScript compiler.
- `index.ts` imports `Interf` but the compiler isn't sure if `Interf` is a type or value, so it keeps it.
- Loading `index.ts` fails because `Interf` is not resolvable

The fix here is declaring that you're importing a type:
```ts
import type { Interf } from './interf.js';
export type { Interf }
```

**Comment by privatenumber** [comment]
Hey, you're coming on a little strong.

When asking a stranger for help online, consider rephrasing your message to sound less accusatory. If you feel entitled to some kind of result, maybe you should at least support the project by contributing or sponsoring first.

Happy to discuss the differences in what you're seeing if you edit your comment to be respectful.

**Comment by privatenumber** [comment]
The problem was the accusatory tone of your message that I'm being misleading, all while being misinformed.

You filed an issue on the project to seek support so you're asking for help. If it was merely an FYI, you'd be ok with a closed issue + explanation. Instead, you argued back prompting for more explanation (basically more help).

---

Anyway, here's why it's expected behavior:

You're comparing a bundlers (tsc, esbuild, swc) to runtimes (tsx, ts-node w/ transpileOnly) which are completely different. Bundlers analyze relevant files when compiling a module. Runtimes don't have this advantage because modules are compiled in isolation. ts-node (without transpileOnly) compiles the entire project with tsc before running it, which is why it's slow.

With [`isolatedModules`](https://esbuild.github.io/content-types/#isolated-modules) enabled, tsc will error:
<img width="992" src="https://github.com/esbuild-kit/tsx/assets/1075694/4f4f01ee-de88-4d6b-99f5-8588850f6d96">

Further explanation in esbuild: https://github.com/evanw/esbuild/issues/1941#issuecomment-1014041320

You might also be interested to learn the motivation for the `import/export type` syntax is precisely this use-case: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html#type-only-imports-and-export

From the PR https://github.com/microsoft/TypeScript/pull/35200:
> At the same time, users who transpile their code file by file (as in Babel, ts-loader in transpileOnly mode) sometimes have the opposite problem, where a re-export of a type should be elided, but the compiler can’t tell that the re-export is only a type during single-file transpilation

BTW, your esbuild snippet doesn't demonstrate anything if you don't share what you're compiling. A link to the [esbuild REPL](https://esbuild.github.io/try/#YgAwLjE5LjMAAGUAZW50cnkuanMA) would've been more insightful.
