### ISSUE TITLE
TS files in dependency require explicit .ts extension

### ISSUE THREAD

**Issue by vlovich** [esbuild-kit/tsx#33]
I have the following:
```
scripts/
  program/
    package.json
    main.ts
  common/
    module.ts <-- exports someMethod
```
In my main.ts I have:
```
import { someMethod } from 'common/module'
```
This fails with 
```
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '.../scripts/program/node_modules/common/module' imported from .../scripts/program/main.ts
Did you mean to import .../scripts/common/module.ts?
```

If I do:
```
import { someMethod } from 'common/module.ts'
```
then it works but VSCode is unhappy & highlights this as an error.

This mostly works with `esbuild-node-loader` without needing to do this.

**Comment by privatenumber** [comment]
This was fixed but seems the [release had failed due to a GitHub API failure](https://github.com/esbuild-kit/esm-loader/actions/runs/2513284962/attempts/1).

Just re-ran and released: https://github.com/esbuild-kit/esm-loader/releases/tag/v2.2.1

Try `npm update` or re-installing tsx to get the sub-dependency upgrade.
