### ISSUE TITLE
add Enter key to restart server for default mode

### ISSUE THREAD

**Issue by doaortu** [esbuild-kit/tsx#364]
### Feature request

the Enter/Return key to restart the server is a great feature, but I think it's currently only available when we pass `watch` argument to the `tsx` command.
Can we add this ability to standard/normal mode?

### Motivations

When I developing backend using `tsx`, I often want to restart the server manually instead of watching the file change, because I often (accidentally) saving the file while I'm editing, and it triggers the server restart, and it happens frequently.

### Alternatives

I think there's workaround for this, by passing `**/*.ts` glob on `watch --ignore` arguments but I haven't tried it.
_Edit: this workaround doesn't work, it simply stuck when I pass the `**/*.ts` glob_

### Contributions

- [ ] I plan to open a pull request for this issue
- [ ] I plan to make a financial contribution to this project

**Comment by privatenumber** [comment]
A lot of reasons why this won't happen (including technical ones). But the simplest answer is that it's out of scope.

tsx is a thin wrapper around Node.js to simply enhance it with TypeScript support. Watch mode was a nicety that I lately regret adding. And since this request has nothing to do with TypeScript, you might as well make this request directly to Node.js. But you can also easily implement server restarting logic in your own code.

**Comment by doaortu** [comment]
Okay, understandable.
Thank you.
