### ISSUE TITLE
Support React 17 automatic runtime

### ISSUE THREAD

**Issue by kilbiller** [esbuild-kit/tsx#71]
### Feature request

https://github.com/evanw/esbuild/releases/tag/v0.14.51 just came out with support for React 17 automatic runtime and it would be great if tsx could support it also.
Ideally just like esbuild with TSConfig resolution so no need to duplicate config.

### Why?

To keep feature parity with esbuild

### Alternatives

Keep importing React in ts files

**Comment by privatenumber** [comment]
This is already supported.

You can run `npm update` to update your `esbuild` because `tsx` uses a [range dependency](https://github.com/esbuild-kit/core-utils/blob/8a8a3d315cd2055fec92183e794b72df40c61892/package.json#L29).

As per [the release notes](https://github.com/evanw/esbuild/releases/tag/v0.14.51), you can configure it to use `automatic` mode via `tsconfig.json#compilerOptions.jsx` & `tsconfig.json#compilerOptions.jsxImportSource`.

**Comment by kilbiller** [comment]
My bad, I should have thought of that first.
Thank you for your time !
