### ISSUE TITLE
Webpack Terser error compiling scss -> f is not defined

### ISSUE THREAD

**Issue by meriturva** [esbuild-kit/tsx#87]
### Bug description

We cannot use tsx to compile our scss using webpack (using ts-node same webpack configuration works correctly)

### Reproduction

Here is a simple repo to reproduce the issue:

https://github.com/meriturva/tsx-webpack-terser-issue

run two scripts on package.json file (one using ts-node, the other using tsx).

### Environment

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 11.28 GB / 31.72 GB
  Binaries:
    Node: 16.17.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.15.0 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    tsx: 3.8.2 => 3.8.2
```

### Can you contribute a fix?

- [ ] I’m interested in opening a pull request for this issue.

**Comment by privatenumber** [comment]
Thanks for the issue.

Seems the problem is with [terser-webpack-plugin](https://github.com/webpack-contrib/terser-webpack-plugin/tree/v5.3.5) (which is enabled by default in Webpack) using Workers to handle minification.

This happens because the minification logic is [passed onto the Worker as a string](https://github.com/webpack-contrib/terser-webpack-plugin/blob/v5.3.5/src/index.js#L497) (the `options` in `serialize(options)` contains the minification logic via [`options.minimizer.implementation`](https://github.com/webpack-contrib/terser-webpack-plugin/blob/v5.3.5/src/index.js#L190). Unfortunately, [esbuild doesn't support stringified functions](https://esbuild.github.io/content-types/#function-tostring) in `eval`s or Workers.

A work around for you is to add this to your Webpack config to disable Terser's use of Workers :
```js
  plugins: [
    new TerserPlugin({
      parallel: false,
    }),
  ]
```

Or use an [alternative minifier like esbuild](https://github.com/privatenumber/esbuild-loader#js-minification-eg-terser).
