### ISSUE TITLE
Improper handling of graceful exits

### ISSUE THREAD

**Issue by gz-95** [esbuild-kit/tsx#95]
### Bug description

`tsx` does not wait for script to exit gracefully before terminating the process.

### Reproduction

Let's say you have `main.ts` as the following:

```
console.log('starting up');

process.on('SIGINT', () => {
  console.log('shutting down');

  // simulate cleanup
  setTimeout(() => {
    console.log('cleanly exiting');
    process.exit(0);
  }, 5000);
});

// run forever
setInterval(() => {}, 1 << 30);
```
Running `main.ts` via `node --no-warnings --loader tsx main.ts` will produce the correct behavior, i.e. pressing `CTRL+C` will signal the script to start cleaning up and then exit gracefully.

On the other hand, when running via `tsx main.ts`, the process will exit abruptly when signaled without waiting for the script to completely finish cleaning up.

### Environment

```shell
System:
    OS: Linux 5.15 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
    CPU: (4) x64 Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
    Memory: 10.00 GB / 15.52 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 18.7.0 - /usr/local/node/bin/node
    npm: 8.15.0 - /usr/local/node/bin/npm
  npmPackages:
    tsx: ^3.8.2 => 3.8.2
```

### Can you contribute a fix?

- [ ] I’m interested in opening a pull request for this issue.

**Comment by privatenumber** [comment]
I investigated this and turns out it's a really difficult problem.

Here are some approaches I considered:

#### 1. Relay kill signals from parent to child process

```ts
import { constants } from 'os'

const uncatchableSignals = ['SIGKILL', 'SIGSTOP']

for (const signal of Object.keys(constants.signals)) {
	if (!uncatchableSignals.includes(signal)) {
		process.on(signal, () => {
			child.kill(signal)
		})
	}
}
```

This works fine when a kill is sent directly to the parent process. But in an interactive shell, pressing <kbd>Ctrl</kbd>+<kbd>C</kbd> sends a `SIGINT` to the process group (both parent and child). When this happens, the child ends up receiving `SIGINT` twice: one from the shell (via <kbd>Ctrl</kbd>+<kbd>C</kbd>) and one relayed from the parent. This is probably a minor issue but could be unexpected for cleanup logic to execute twice.

Additionally, this approach prevents graceful exists on Windows. Since Windows doesn't have signals, Node.js listens for <kbd>Ctrl</kbd>+<kbd>C</kbd> on `stdin` so it can be caught. But when a `SIGINT` (programmatic kill) is received, it terminates the process immediately regardless of a handler:
> Sending `SIGINT`, `SIGTERM`, and `SIGKILL` will cause the unconditional termination of the target process, and afterwards, subprocess will report that the process was terminated by signal.
>
> -[Process#Signal events | Node.js](https://nodejs.org/api/process.html#signal-events:~:text=Sending%20SIGINT%2C%20SIGTERM%2C%20and%20SIGKILL%20will%20cause%20the%20unconditional%20termination%20of%20the%20target%20process%2C%20and%20afterwards%2C%20subprocess%20will%20report%20that%20the%20process%20was%20terminated%20by%20signal.)

FWIW this is [how `ts-node` seems to handle it](https://github.com/TypeStrong/ts-node/blob/97f9afd046b66a0fe05a7d76e7a32f94b872016f/src/child/spawn-child.ts#L40-L42).

#### 2. Ignore kill signals on parent process

```ts
import { constants } from 'os'

const noop = () => {}
const uncatchableSignals = ['SIGKILL', 'SIGSTOP']

for (const signal of Object.keys(constants.signals)) {
	if (!uncatchableSignals.includes(signal)) {
		// Let shell send signals to child directly
		process.on(signal, noop)
	}
}
```

To prevent the signal from being received twice, I figured maybe we can ignore signals on the parent and let the shell send them to the child directly (e.g. on <kbd>Ctrl</kbd>+<kbd>C</kbd>).

However, this disables programmatic `kill`s from being handled by the parent so spawning tsx as a child process will not be gracefully killable.

#### 3. Detached child process

```ts
import { spawn } from 'child_process'

spawn(process.execPath, process.argv.slice(1), {
	stdio: 'inherit',
	detached: true
})
```

On Linux/Mac, [detaching the child process](https://nodejs.org/api/child_process.html#optionsdetached) while inherting the `stdio` allowed <kbd>Ctrl</kbd>+<kbd>C</kbd> to only be sent to the parent process (likely because they were no longer in the same process group).

This was convenient because the parent can relay the kill signal to the child and it wouldn't be sent again by the shell. However, on Windows, detaching the child seemed to prevent `stdio` from getting inherited (Node.js bug? Windows limitation?). None of the child's `stdout` would be visible.

**Comment by gz-95** [comment]
@privatenumber thanks for spending time looking into it. Given the circumstances, I think it's reasonable for the child process to handle duplicated signals by not initiating another shutdown procedure if one is already in progress.

Thanks again for your hard work!

**Comment by privatenumber** [comment]
I actually managed to prevent double signal receiving and also preserve Windows support for <kbd>Ctrl</kbd> + <kbd>C</kbd>.

Will release shortly.
